#!/usr/bin/env bash
#Sets nginx for listening to a port 80

#creates a symbolic link (-s option) between the nginx configuration file
# and enabled sites directory
ln -sf /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
# restart nginx
service nginx start
# terminates the first nginx process ID
kill "$(pgrep 'nginx' | head -l)"
